name: Build and Commit JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '22'  # Set your desired Java version

      - name: Build with Maven
        run: mvn clean package

      - name: Copy JAR file to repository
        run: cp *.jar ./  # Adjust the path as per your Maven output directory

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"

      - name: Commit changes
        run: |
          git add *.jar
          git commit -m "Add generated JAR file"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

